spring.application.name=authservice
spring.datasource.url= // Configurar URL do banco de dados
spring.datasource.username= // Configurar usuário do banco de dados
spring.datasource.password= // Configurar senha do banco de dados
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.HSQLDialect

server.error.include-stacktrace=never
spring.jpa.hibernate.ddl-auto=update

api.security.token.secret=${JWT_Secret} // Configurar Token em variáveis de ambiente
server.port=8081 // Configurar porta do servidor
